### ISSUE TITLE
Unable to export conformance report

### ISSUE THREAD

**Issue by csm-aut** [csm-aut/csm#21]
ERROR:Server error!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(_args, *_kwargs)
  File "/usr/local/csm/csmserver/views/conformance.py", line 482, in api_get_conformance_report_software_profile_packages
    smu_info = smu_loader.get_smu_info(software_profile_package.replace('.' + smu_loader.file_suffix,''))
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by csm-aut** [comment]
This happens when the smu_meta table contains no release data.  To fix this issue, add smu_info_loader .is_valid check.
