### ISSUE TITLE
Out of range value for 'compressed_image_size', download release software not working.

### ISSUE THREAD

**Issue by smjurcak** [csm-aut/csm#23]
Issue found on http://10.64.117.201:5000/ by Amit Singh (amitsi4) on 1/20/2106.
1. When trying to download release software, all prompts work as expected, but the download never appears in Download Dashboard and nothing is downloaded.
2. When navigating to the cco lookup for 5.1.1, the following traceback is recorded in system logs.

Traceback (most recent call last):
File "/usr/local/csm/csmserver/smu_info_loader.py", line 139, in get_smu_info_from_cco
db_session.flush()
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
self._flush(objects)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
transaction.rollback(_capture_exception=True)
File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
compat.reraise(exc_type, exc_value, exc_tb)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
flush_context.execute()
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
rec.execute(self)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
uow
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
mapper, table, insert)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 570, in _emit_insert_statements
execute(statement, multiparams)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
return meth(self, multiparams, params)
File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
compiled_sql, distilled_params
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
context)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
exc_info
File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb)
File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 928, in _execute_context
context)
File "/usr/lib/python2.7/site-packages/sqlalchemy/connectors/mysqldb.py", line 68, in do_executemany
rowcount = cursor.executemany(statement, parameters)
File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 155, in executemany
self._get_db().encoding)
File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 182, in _do_execute_many
rows += self.execute(sql)
File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 135, in execute
result = self._query(query)
File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 274, in _query
conn.query(q)
File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 714, in query
self._affected_rows = self._read_query_result(unbuffered=unbuffered)
File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 865, in _read_query_result
result.read()
File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1062, in read
first_packet = self.connection._read_packet()
File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 830, in _read_packet
packet.check_error()
File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 348, in check_error
raise_mysql_exception(self._data)
File "/usr/lib/python2.7/site-packages/pymysql/err.py", line 116, in raise_mysql_exception
_check_mysql_exception(errinfo)
File "/usr/lib/python2.7/site-packages/pymysql/err.py", line 109, in _check_mysql_exception
raise errorclass(errno,errorvalue)
DataError: (DataError) (1264, u"Out of range value for column 'compressed_image_size' at row 42") 'INSERT INTO smu_info (id, name, status, type, package_type, posted_date, eta_date, ddts, description, impact, cco_filename, functional_areas, package_bundles, `composite_DDTS`, compressed_image_size, uncompressed_image_size, supersedes, superseded_by, prerequisites, prerequisite_to, platform_release) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)' (('AA08276', 'asr9k-px-5.1.1.CSCum43655', 'Posted', 'Optional', 'SMU', '03/10/2014 11:06:11 PDT', '04/13/2014 00:00:00 PDT', 'CSCum43655', 'IPv6 Traffic drop on Bundle interface No shut due to Incomplete Nexthop', 'ISSU/Reload', 'asr9k-px-5.1.1.CSCum43655.tar', 'CEF', 'asr9k-mini-px', '', 5766464, 32998063, '', '', '', None, 'asr9k_px_5.1.1'), ('AA08282', 'asr9k-px-5.1.1.CSCul39674', 'Posted', 'Recommended', 'SMU', '03/05/2014 17:03:37 PST', '04/13/2014 00:00:00 PDT', 'CSCul39674', 'Fabric link retrain between typhoon and RSP440 (RX)', 'Needs Reboot', 'asr9k-px-5.1.1.CSCul39674.tar', 'FABRIC', 'asr9k-mini-px', '', 938276, 23103104, '', '', '', None, 'asr9k_px_5.1.1'), ('AA08305', 'asr9k-px-5.1.1.CSCun15817', 'Posted', 'Optional', 'SMU', '04/07/2014 11:11:11 PDT', '04/07/2014 00:00:00 PDT', 'CSCun15817', 'Umbrella DDTS for PVRST on 5.1.1', 'Hitless', 'asr9k-px-5.1.1.CSCun15817.tar', 'ETHER', 'asr9k-mini-px', 'CSCul81352,CSCul57214,CSCul88181', 1155946, 3743425, '', '', '', None, 'asr9k_px_5.1.1'), ('AA08336', 'asr9k-px-5.1.1.CSCun49297', 'Posted', 'Optional', 'SMU', '03/17/2014 11:06:25 PDT', '03/17/2014 00:00:00 PDT', 'CSCun49297', 'Umbrella DDTS for CSCun08658, CSCun11188 and CSCum89257', 'ISSU/Reload', 'asr9k-px-5.1.1.CSCun49297.tar', 'INFRASTRUCTURE', 'asr9k-mini-px', 'CSCun11188,CSCun08658,CSCum89257', 2504987, 7183811, '', 'asr9k-px-5.1.1.CSCun81835', '', None, 'asr9k_px_5.1.1'), ('AA08339', 'asr9k-px-5.1.1.CSCun21356', 'Posted', 'Optional', 'SMU', '03/24/2014 10:44:57 PDT', '', 'CSCun21356', 'low cps rate observed when large number of circuit id config', 'Hitless', 'asr9k-px-5.1.1.CSCun21356.tar', 'DHCP', 'asr9k-mini-px', '', 1880076, 8518743, '', '', '', None, 'asr9k_px_5.1.1'), ('AA08340', 'asr9k-px-5.1.1.CSCun18394', 'Posted', 'Optional', 'SMU', '03/25/2014 13:43:30 PDT', '03/25/2014 00:00:00 PDT', 'CSCun18394', 'Show subscriber session filter for outer vlan is not working', 'Hitless', 'asr9k-px-5.1.1.CSCun18394.tar', 'BNG', 'asr9k-bng-px', '', 6085804, 55128680, '', 'asr9k-px-5.1.1.CSCuq01085', '', None, 'asr9k_px_5.1.1'), ('AA08375', 'asr9k-px-5.1.1.CSCun77121', 'Posted', 'Optional', 'SMU', '04/02/2014 15:51:34 PDT', '04/21/2014 00:00:00 PDT', 'CSCun77121', 'RSVP Mem leakage 5.1.0', 'Hitless', 'asr9k-px-5.1.1.CSCun77121.tar', 'MPLS-TE', 'asr9k-mpls-px', '', 1857581, 5672413, '', '', '', None, 'asr9k_px_5.1.1'), ('AA08386', 'asr9k-px-5.1.1.CSCun19780', 'Posted', 'Optional', 'SMU', '05/08/2014 17:33:25 PDT', '', 'CSCun19780', 'fpd upgrade fails on A9K-2x100GE and A9K-1x100GE', 'ISSU/Reload', 'asr9k-px-5.1.1.CSCun19780.tar', 'FPD', 'asr9k-mini-px', '', 75494765, 82416886, '', '', '', None, 'asr9k_px_5.1.1') ... displaying 10 of 43 total bound parameter sets ... ('ASR9K-iosxr-px-5.1.1.tar', 'ASR9K-iosxr-px-5.1.1.tar', 'Posted', '', 'Software', '', '', '', '', '', 'ASR9K-iosxr-px-5.1.1.tar', '', '', '', 2942535680, 0, '', '', '', None, 'asr9k_px_5.1.1'), ('ASR9K-iosxr-px-k9-5.1.1.tar', 'ASR9K-iosxr-px-k9-5.1.1.tar', 'Posted', '', 'Software', '', '', '', '', '', 'ASR9K-iosxr-px-k9-5.1.1.tar', '', '', '', 2953256960, 0, '', '', '', None, 'asr9k_px_5.1.1'))

**Comment by csm-aut** [comment]
Fixed by changing the compressed_image_size and uncompressed_image_size column type from integer to varchar(20)
