### ISSUE TITLE
Downloading CCO content fails

### ISSUE THREAD

**Issue by brona** [csm-aut/csm#34]
While using 3.2.1 or master trying to download SMUs always fails with following error:
(Using "Validate" button in User Preferences for CCO credentials passes OK).
(I can download SMUs with my account manually from software.cisco.com)

```
Traceback (most recent call last):
File "/opt/csm/csmserver/work_units/download_work_unit.py", line 99, in start
bsd.download(output_file_path, callback=self.progress_listener)
File "/opt/csm/csmserver/cisco_service/bsd_service.py", line 120, in download
raise Exception(message)
Exception: User "**CENSORED**" may not have software download privilege on cisco.com.
```

**Comment by csm-aut** [comment]
Is this same a problem for you?  To find the reason, I will need your username and password.  You can temporary change your CCO password first.

**Comment by jlixfeld** [comment]
Hi,

I just encountered this issue too on 3.3.  Validate passes, and I can download the same SMU from cco from a web browser with the same login and pass that I validated on CSM Server.
